fixed static version bug

diff --git a/Dockerfile.scheduler b/Dockerfile.scheduler
--- a/Dockerfile.scheduler
+++ b/Dockerfile.scheduler
@@ -23,20 +23,16 @@ LABEL maintainer="Fossology <fossology@fossology.org>"
 RUN DEBIAN_FRONTEND=noninteractive apt-get update \
     && DEBIAN_FRONTEND=noninteractive apt-get install postgresql postgresql-contrib -y
 
-COPY --from=builder /fossology_packages/fossology/packages/fossology-common_3.10.0.151~rc1-1_amd64.deb .
-COPY --from=builder /fossology_packages/fossology/packages/fossology-db_3.10.0.151~rc1-1_amd64.deb .
-COPY --from=builder /fossology_packages/fossology/packages/fossology-scheduler_3.10.0.151~rc1-1_amd64.deb .
+COPY --from=builder /fossology_packages/fossology/packages/fossology-common_*_amd64.deb .
+COPY --from=builder /fossology_packages/fossology/packages/fossology-db_*_amd64.deb .
+COPY --from=builder /fossology_packages/fossology/packages/fossology-scheduler_*_amd64.deb .
 
 RUN DEBIAN_FRONTEND=noninteractive apt-get update \
     && pg_ctlcluster 11 main start && service postgresql start && service postgresql status\
-    && dpkg -i fossology-common_3.10.0.151~rc1-1_amd64.deb fossology-scheduler_3.10.0.151~rc1-1_amd64.deb fossology-db_3.10.0.151~rc1-1_amd64.deb || echo "deb failed" \
+    && dpkg -i fossology-common_*_amd64.deb fossology-scheduler_*_amd64.deb fossology-db_*_amd64.deb || echo "deb failed" \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y -f
 
-COPY --from=builder /fossology_packages/fossology/packages/fossology-web_3.10.0.151~rc1-1_amd64.deb .
-
-RUN DEBIAN_FRONTEND=noninteractive apt-get update \
-    && dpkg -i fossology-web_3.10.0.151~rc1-1_amd64.deb || echo "deb failed" \
-    && DEBIAN_FRONTEND=noninteractive apt-get install -y -f
+COPY ./src/www/ui/core-schema.dat /usr/share/fossology/www/ui/
 
 COPY ./docker-entrypoint.sh /fossology/docker-entrypoint.sh
 RUN chmod +x /fossology/docker-entrypoint.sh
